replicaCount: 1

image:
  repository: link-shortener-redirect-service
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  name: link-shortener-redirect-service

spring:
  profiles:
    active: "default"

resources:
  requests:
    cpu: "50m"
    memory: "384Mi"
  limits:
    cpu: "1"
    memory: "768Mi"

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0"

vault:
  role: ""
  secretPath: ""
  secretTemplate: ""