replicaCount: 1

spring:
  profiles:
    active: "dev"
env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"

vault:
  role: link-shortener-redirect-service-dev-role
  secretPath: kv/data/dev/link-shortener-redirect-service/config
  secretTemplate: |
    {{- with secret "kv/data/dev/link-shortener-redirect-service/config" -}}
    {{- range $key, $value := .Data.data }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}